//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParkingSystemEntities : DbContext
    {
        public ParkingSystemEntities()
            : base("name=ParkingSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserMaster> UserMasters { get; set; }
        public DbSet<VerificationOTP> VerificationOTPs { get; set; }
        public DbSet<ApiToken> ApiTokens { get; set; }
        public DbSet<APIUser> APIUsers { get; set; }
        public DbSet<ExceptionLog> ExceptionLogs { get; set; }
    }
}
