//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster
    {
        public UserMaster()
        {
            this.VerificationOTPs = new HashSet<VerificationOTP>();
            this.ApiTokens = new HashSet<ApiToken>();
        }
    
        public int UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<VerificationOTP> VerificationOTPs { get; set; }
        public virtual ICollection<ApiToken> ApiTokens { get; set; }
    }
}
